include:
  - project: 'sertiscorp/devops/gitlab-ci-templates'
    ref: master
    file: 'base.yaml'

Unit Test:
  stage: test
  image: node:14-alpine
  script:
    - yarn install
    - yarn run test
  coverage: '/All files\s*\|\s*(\d*.\d*|\d*)\s*\|\s*(\d*.\d*|\d*)\s*\|\s*(\d*.\d*|\d*)\s*\|\s*(\d*.\d*|\d*)\s*\|/'
  rules:
    - if: '($CI_MERGE_REQUEST_SOURCE_BRANCH_NAME != "master" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop") || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: always
      allow_failure: false

Linting:
  stage: test
  image: node:14-alpine
  script:
    - yarn install --dev
    - yarn run lint
  rules:
    - if: '($CI_MERGE_REQUEST_SOURCE_BRANCH_NAME != "master" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop") || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: always
      allow_failure: false

Build package:
  stage: build
  image: node:14-alpine
  script:
    - yarn install
    - yarn build
    - |
      if [[ ! -f .npmrc ]]; then
        {
          echo '@${CI_PROJECT_ROOT_NAMESPACE}:registry=https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/'
          echo '//gitlab.com/api/v4/packages/npm/:_authToken=${CI_JOB_TOKEN}'
          echo '//gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}'
        } >> .npmrc
      fi
    - npm publish
