version: '3.3'

services:
  cassandra:
      image: cassandra:3
      container_name: cassandra
      ports:
        - "9042:9042"
      environment:
        - "MAX_HEAP_SIZE=256M"
        - "HEAP_NEWSIZE=128M"
      restart: always
      volumes:
        - ./cassandra/cassandra.yaml:/etc/cassandra/cassandra.yaml
        - ./data/db:/var/lib/cassandra
        - "./data/log/cassandra/${APP_ENV}:/var/log/cassandra"

  cassandra-load-keyspace:
      container_name: cassandra-load-keyspace
      image: cassandra:3
      depends_on:
        - cassandra
      volumes:
        - ./cassandra/broadcast.keyspace.${APP_ENV}.cql:/schema.cql 
      command: /bin/bash -c "sleep 60 && echo loading cassandra keyspace && cqlsh -u cassandra -p cassandra cassandra -f /schema.cql"